using Microsoft.SqlServer.TransactSql.ScriptDom;
using Microsoft.VisualStudio.Extensibility;
using Microsoft.VisualStudio.Extensibility.DebuggerVisualizers;
using Microsoft.VisualStudio.Extensibility.VSSdkCompatibility;
using Microsoft.VisualStudio.RpcContracts.RemoteUI;
using Microsoft.VisualStudio.Shell;
using Newtonsoft.Json;

namespace MarkMpn.ScriptDom.DebugVisualizer.DebuggerSide
{
    /// <summary>
    /// Debugger visualizer provider for <see cref="IRootExecutionPlanNode"/>.
    /// </summary>
    [VisualStudioContribution]
    internal class ExecutionPlanDebuggerVisualizerProvider : DebuggerVisualizerProvider
    {
        private const string DisplayName = "MarkMpn.ScriptDom.DebugVisualizer.DisplayName";

        public override DebuggerVisualizerProviderConfiguration DebuggerVisualizerProviderConfiguration => new(
            new VisualizerTargetType($"%{DisplayName}%", typeof(TSqlScript)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(TSqlBatch)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ExecuteStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterViewStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateViewStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateOrAlterViewStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTriggerStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateTriggerStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateOrAlterTriggerStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterProcedureStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateProcedureStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateOrAlterProcedureStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DeclareTableVariableStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SelectStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterFunctionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BeginEndBlockStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BeginEndAtomicBlockStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BeginTransactionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BreakStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CommitTransactionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(RollbackTransactionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SaveTransactionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ContinueStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateDefaultStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateFunctionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateOrAlterFunctionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateRuleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DeclareVariableStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(GoToStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(IfStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(LabelStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(WhileStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DeleteStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(InsertStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(UpdateStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateSchemaStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(WaitForStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ReadTextStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(UpdateTextStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(WriteTextStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(LineNoStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(GrantStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DenyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(RevokeStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterAuthorizationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(GrantStatement80)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DenyStatement80)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(RevokeStatement80)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(PrintStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateSequenceStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterSequenceStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropSequenceStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateSecurityPolicyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterSecurityPolicyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropSecurityPolicyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateColumnMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropColumnMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateColumnEncryptionKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterColumnEncryptionKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropColumnEncryptionKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateExternalTableStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropExternalTableStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateExternalDataSourceStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterExternalDataSourceStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropExternalDataSourceStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateExternalStreamStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropExternalStreamStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateExternalFileFormatStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropExternalFileFormatStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateExternalStreamingJobStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropExternalStreamingJobStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateAssemblyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterAssemblyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateXmlSchemaCollectionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterXmlSchemaCollectionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropXmlSchemaCollectionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableAlterPartitionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableRebuildStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableChangeTrackingModificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableFileTableNamespaceStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableSetStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableAddTableElementStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableConstraintModificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableSwitchStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableDropTableElementStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableTriggerModificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(EnableDisableTriggerStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(TryCatchStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateTypeUdtStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateTypeUddtStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateSynonymStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterRouteStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateRouteStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterQueueStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateQueueStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(IndexDefinition)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateXmlIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateSelectiveXmlIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateFullTextIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateEventNotificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateApplicationRoleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterApplicationRoleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateRoleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterRoleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateServerRoleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServerRoleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropServerRoleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateUserStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterUserStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateStatisticsStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(UpdateStatisticsStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ReturnStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DeclareCursorStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SetVariableStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(OpenCursorStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CloseCursorStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(OpenSymmetricKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CloseSymmetricKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(OpenMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CloseMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DeallocateCursorStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(FetchCursorStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropDatabaseStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropStatisticsStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropTableStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropProcedureStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropFunctionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropViewStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropDefaultStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropRuleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropTriggerStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropSchemaStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(RaiseErrorLegacyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(RaiseErrorStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ThrowStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(UseStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(KillStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(KillQueryNotificationSubscriptionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(KillStatsJobStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CheckpointStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ReconfigureStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ShutdownStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SetUserStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(TruncateTableStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(PredicateSetStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SetStatisticsStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SetRowCountStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SetOffsetsStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SetCommandStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SetTransactionIsolationLevelStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SetTextSizeStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SetIdentityInsertStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SetErrorLevelStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateDatabaseStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseScopedConfigurationSetStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseScopedConfigurationClearStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseCollateStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseRebuildLogStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseAddFileStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseAddFileGroupStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseRemoveFileGroupStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseRemoveFileStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseModifyNameStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseModifyFileStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseModifyFileGroupStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseSetStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableAlterIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterTableAlterColumnStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateTableStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(RenameEntityStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CopyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BackupDatabaseStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BackupTransactionLogStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(RestoreStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BulkInsertStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(InsertBulkStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DbccStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateAsymmetricKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreatePartitionFunctionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreatePartitionSchemeStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateRemoteServiceBindingStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterRemoteServiceBindingStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterCertificateStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateCertificateStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateContractStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateCredentialStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterCredentialStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateMessageTypeStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterMessageTypeStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateAggregateStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateEndpointStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterEndpointStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateSymmetricKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterSymmetricKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateFullTextCatalogStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterFullTextCatalogStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateServiceStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServiceStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropPartitionFunctionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropPartitionSchemeStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropSynonymStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropAggregateStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropAssemblyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropApplicationRoleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropFullTextCatalogStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropFullTextIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropLoginStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropRoleStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropTypeStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropUserStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropSymmetricKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropAsymmetricKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropCertificateStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropCredentialStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterPartitionFunctionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterPartitionSchemeStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterFullTextIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateSearchPropertyListStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterSearchPropertyListStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropSearchPropertyListStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateLoginStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterLoginOptionsStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterLoginEnableDisableStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterLoginAddDropCredentialStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(RevertStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropContractStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropEndpointStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropMessageTypeStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropQueueStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropRemoteServiceBindingStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropRouteStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropServiceStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AddSignatureStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropSignatureStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropEventNotificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ExecuteAsStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(EndConversationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(MoveConversationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(GetConversationGroupStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ReceiveStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SendStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterSchemaStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterAsymmetricKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServiceMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BeginConversationTimerStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BeginDialogStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BackupCertificateStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BackupServiceMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(RestoreServiceMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(BackupMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(RestoreMasterKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(SelectStatementSnippet)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(TSqlStatementSnippet)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(MergeStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateTypeTableStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AddSensitivityClassificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropSensitivityClassificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateDatabaseAuditSpecificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseAuditSpecificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropDatabaseAuditSpecificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateServerAuditSpecificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServerAuditSpecificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropServerAuditSpecificationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateServerAuditStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServerAuditStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropServerAuditStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateDatabaseEncryptionKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterDatabaseEncryptionKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropDatabaseEncryptionKeyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ResourcePoolStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateResourcePoolStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterResourcePoolStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropResourcePoolStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(ExternalResourcePoolStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateExternalResourcePoolStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterExternalResourcePoolStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropExternalResourcePoolStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateWorkloadGroupStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterWorkloadGroupStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropWorkloadGroupStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateWorkloadClassifierStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropWorkloadClassifierStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateBrokerPriorityStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterBrokerPriorityStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropBrokerPriorityStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateFullTextStopListStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterFullTextStopListStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropFullTextStopListStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateCryptographicProviderStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterCryptographicProviderStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropCryptographicProviderStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(EventSessionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateEventSessionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterEventSessionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropEventSessionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterResourceGovernorStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateSpatialIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServerConfigurationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServerConfigurationSetExternalAuthenticationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServerConfigurationSetBufferPoolExtensionStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServerConfigurationSetDiagnosticsLogStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServerConfigurationSetFailoverClusterPropertyStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServerConfigurationSetHadrClusterStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterServerConfigurationSetSoftNumaStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateAvailabilityGroupStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterAvailabilityGroupStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropAvailabilityGroupStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateFederationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterFederationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropFederationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(UseFederationStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DiskStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateColumnStoreIndexStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateExternalLibraryStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterExternalLibraryStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropExternalLibraryStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(CreateExternalLanguageStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(AlterExternalLanguageStatement)),
            new VisualizerTargetType($"%{DisplayName}%", typeof(DropExternalLanguageStatement)))
        {
            VisualizerObjectSourceType = new("MarkMpn.ScriptDom.DebugVisualizer.DebugeeSide.ScriptDomObjectSource, MarkMpn.ScriptDom.DebugVisualizer.DebugeeSide")
        };

        public override async Task<IRemoteUserControl> CreateVisualizerAsync(VisualizerTarget visualizerTarget, CancellationToken cancellationToken)
        {
            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);
            var wrapper = new WpfControlWrapper(new ScriptDomUserControl(() => GetTargetFragmentAsync(visualizerTarget, cancellationToken)));
            return wrapper;
        }

        private async Task<TSqlFragment> GetTargetFragmentAsync(VisualizerTarget visualizerTarget, CancellationToken cancellationToken)
        {
            var serializedFragment = await visualizerTarget.ObjectSource.RequestDataAsync<SerializedFragment>(null, cancellationToken);
            var settings = new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.Auto
            };
            return JsonConvert.DeserializeObject<TSqlFragment>(serializedFragment.Fragment, settings);
        }
    }
}
